###### These exercises are inspired from Andrew Ng Coursera Deep Learning specialisation and INRIA FUN MOOC on Python 

Broadcasting in python is a mecanism which duplicates a scalar or vector to perform elementwise operations on matrix or vectors

In [1]:
import numpy as np
A = np.random.rand(4,3)
print(A)

[[0.34643498 0.95678443 0.08441256]
 [0.61644992 0.99758413 0.24404046]
 [0.67905183 0.42475856 0.82300463]
 [0.49401663 0.84481113 0.11461532]]


For instance, we can broadcast a scalar b to add b to each element of A

In [2]:
b = 2
A + b

array([[2.34643498, 2.95678443, 2.08441256],
       [2.61644992, 2.99758413, 2.24404046],
       [2.67905183, 2.42475856, 2.82300463],
       [2.49401663, 2.84481113, 2.11461532]])

to sum horizontally the elements of A, we can call sum on A with the argument axis = 1

In [3]:
A.sum(axis= 1)

array([1.38763198, 1.85807451, 1.92681503, 1.45344309])

to sum vertically, the argument is axis =0

We can do elementwise operations between a matrix with a vector thanks to python broadcasting.
Let's define a vector u as the vertical sum of all columns of A and use it on A

In [4]:
u = A.sum(axis = 0)
print(u)
print(u.shape)

[2.13595337 3.22393826 1.26607298]
(3,)


For security reshape u to force its shape (1,3). Defining a vector with only one dimension, leaving the other empty such as u is defined above, can have terrible cost in debugging.

In [20]:
u = u.reshape(1,3)
print(u)
print(u.shape)

[[2.13595337 3.22393826 1.26607298]]
(1, 3)


divide A by u

In [6]:
div = A/u
print(div)

[[0.1621922  0.29677505 0.06667275]
 [0.28860645 0.30943028 0.19275387]
 [0.3179151  0.13175146 0.65004518]
 [0.23128624 0.26204321 0.09052821]]


We have broadcasted vector u on each element of A

Exercise:
compute, for each values of A, its percentage in regard of the total column sum of A and store it in a object w

In [7]:
print(A)
print(u)

[[0.34643498 0.95678443 0.08441256]
 [0.61644992 0.99758413 0.24404046]
 [0.67905183 0.42475856 0.82300463]
 [0.49401663 0.84481113 0.11461532]]
[[2.13595337 3.22393826 1.26607298]]


In [8]:
w = A/u*100
print(w)

[[16.21922029 29.67750483  6.66727476]
 [28.86064512 30.94302839 19.27538651]
 [31.79151016 13.17514573 65.00451752]
 [23.12862443 26.20432105  9.05282121]]


In [9]:
sum(w)

array([100., 100., 100.])

Lets define two matrix with different dimensions, (3, 1) and (1, 5)

In [10]:
col = np.arange(1, 4).reshape((3, 1))
print(col)

[[1]
 [2]
 [3]]


In [11]:
line = 100 * np.arange(1, 6)
print(line)

[100 200 300 400 500]


Add the two matrix col and line thanks to broadcasting

In [12]:
m = col + line
print(m)

[[101 201 301 401 501]
 [102 202 302 402 502]
 [103 203 303 403 503]]


Broacasting base rules  
We can broadcast A and B when there is a dimension C which 'spreads' both these of A and B  
So we can only broadcast from 1 to n.  
If there is a dimension p> 1 dividing n,  we cannot broadcast from p to n.

Define  

A with dimensions  15 x 3 x 5  
B with dimensions  15 x 1 x 5  
verify A+B has dimensions 15 x 3 x 5  

Try also for 

B is dimensions 3 x 5  
B is dimensions 3 x 1  
B is dimensions 1  

In [13]:
A = np.random.rand(15,3,5)
B = np.random.rand(15,1,5)

In [14]:
A.shape
B.shape

(15, 1, 5)

In [15]:
C = A+B

In [16]:
C.shape

(15, 3, 5)

Define A and B with following dimensions and check if you can broadcast

A shape as: 2 x 1

B shape as:  8 x 4 x 3

In [17]:
A = np.random.rand(2,1)
B = np.random.rand(8, 4,3)

In [18]:
print(A.shape)
print(B.shape)

(2, 1)
(8, 4, 3)


In [19]:
A = A.reshape(2,1,1)
print(A.shape)
print(B.shape)

(2, 1, 1)
(8, 4, 3)


we would need p > 1 dimension to broadcast (i.e. 4, 4, 3), so no solution