###### These exercises are inspired from Andrew Ng Coursera Deep Learning specialisation and INRIA FUN MOOC on Python 

Broadcasting in python is a mecanism which duplicates a scalar or vector to perform elementwise operations on matrix or vectors

In [1]:
import numpy as np
A = np.random.rand(4,3)
print(A)

[[0.67944041 0.09299046 0.06495267]
 [0.75694481 0.57858399 0.04206059]
 [0.02993282 0.26695851 0.45542551]
 [0.52890305 0.72685075 0.07957926]]


For instance, we can broadcast a scalar b to add b to each element of A

In [2]:
b = 2
A + b

array([[2.67944041, 2.09299046, 2.06495267],
       [2.75694481, 2.57858399, 2.04206059],
       [2.02993282, 2.26695851, 2.45542551],
       [2.52890305, 2.72685075, 2.07957926]])

to sum horizontally the elements of A, we can call sum on A with the argument axis = 1

In [3]:
A.sum(axis= 1)

array([0.83738354, 1.37758939, 0.75231684, 1.33533306])

to sum vertically, the argument is axis =0

We can do elementwise operations between a matrix with a vector thanks to python broadcasting.
Let's define a vector u as the vertical sum of all columns of A and use it on A

In [4]:
u = A.sum(axis = 0)
print(u)
print(u.shape)

[1.9952211  1.66538371 0.64201803]
(3,)


For security reshape u to force its shape (1,3). Defining a vector with only one dimension, leaving the other empty such as u is defined above, can have terrible cost in debugging.

In [5]:
u = u.reshape(1,3)
print(u.shape)

(1, 3)


divide A by u

In [6]:
div = A/u
print(div)

[[0.3405339  0.05583726 0.10116955]
 [0.37937891 0.34741783 0.06551309]
 [0.01500226 0.1602985  0.70936561]
 [0.26508493 0.43644642 0.12395175]]


We have broadcasted vector u on each element of A

Exercise:
compute, for each values of A, its percentage in regard of the total column sum of A and store it in a object w

In [12]:
print(A)
print(u)

[[0.67944041 0.09299046 0.06495267]
 [0.75694481 0.57858399 0.04206059]
 [0.02993282 0.26695851 0.45542551]
 [0.52890305 0.72685075 0.07957926]]
[[1.9952211  1.66538371 0.64201803]]


In [14]:
w = A/u*100
print(w)

[[34.05338953  5.58372564 10.11695462]
 [37.93789137 34.74178291  6.55130927]
 [ 1.50022572 16.02984991 70.93656112]
 [26.50849338 43.64464154 12.39517499]]


In [16]:
sum(w)

array([100., 100., 100.])

Lets define two matrix with different dimensions, (3, 1) and (1, 5)

In [17]:
col = np.arange(1, 4).reshape((3, 1))
print(col)

[[1]
 [2]
 [3]]


In [18]:
line = 100 * np.arange(1, 6)
print(line)

[100 200 300 400 500]


Add the two matrix col and line thanks to broadcasting

In [19]:
m = col + line
print(m)

[[101 201 301 401 501]
 [102 202 302 402 502]
 [103 203 303 403 503]]


Broacasting base rules  
We can broadcast A and B when there is a dimension C which 'spreads' both these of A and B  
So we can only broadcast from 1 to n.  
If there is a dimension p> 1 dividing n,  we cannot broadcast from p to n.

Define  

A with dimensions  15 x 3 x 5  
B with dimensions  15 x 1 x 5  
verify A+B has dimensions 15 x 3 x 5  

Try also for 

B is dimensions 3 x 5  
B is dimensions 3 x 1  
B is dimensions 1  

In [20]:
A = np.random.rand(15,3,5)
B = np.random.rand(15,1,5)

In [25]:
A.shape
B.shape

(15, 1, 5)

In [21]:
C = A+B

In [22]:
C.shape

(15, 3, 5)

Define A and B with following dimensions and check if you can broadcast

A shape as: 2 x 1

B shape as:  8 x 4 x 3

In [36]:
A = np.random.rand(2,1)
B = np.random.rand(8, 4,3)

In [37]:
print(A.shape)
print(B.shape)

(2, 1)
(8, 4, 3)


In [64]:
A = A.reshape(2,1,1)
print(A.shape)
print(B.shape)

(2, 1, 1)
(8, 4, 3)


we would need p > 1 dimension to broadcast (i.e. 4, 4, 3), so no solution