###### These exercises are inspired from Andrew Ng Coursera Deep Learning specialisation and INRIA MOOC on FUN platform

In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


###### Benchmark a vectorised and an non vectorized version of the dot product

In [2]:
b = np.random.rand(1000000)
c = np.random.rand(1000000)

import time
time1 = time.time()
d = np.dot(b, c)
print(d)
time2 = time.time()

print("runtime vectorized = " +str(1000*(time2-time1)) + "ms")

250247.7283726234
runtime vectorized = 108.69145393371582ms


In [3]:
time1 = time.time()

e = 0
for i in range(1000000):
    e += b[i]*c[i]
print(e)
time2 = time.time()
print("runtime non vectorized = " +str(1000*(time2-time1)) + "ms")

250247.72837262778
runtime non vectorized = 626.3253688812256ms


###### Exercises

Turn the following imperative method into a vectorized computation using numpy.
 
   - apply the exponential operation to each element of a vector u.
   - we will store the outputs in a vector w of same dimensions than u.    


In [4]:
import math
n=3
u = np.random.rand(n)
v = np.zeros((n, 1))

print(v)
print(u)

for i in range(n):
    v[i]= math.exp(u[i])
print(v)

[[0.]
 [0.]
 [0.]]
[0.28043486 0.8525271  0.39437764]
[[1.32370531]
 [2.34556686]
 [1.48346066]]


Do the same on a matrix A of dimension 4 by 3 and store the results in an object z.  
Generate A with the random method of numpy.

Compute Ax + b, assuming x is a vector of same length that A rows and b is a scalar.  
Generate A and x with the random method of numpy.